version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: nodeshift
    versions:
    - 7.5.0
    - 8.0.0
    - 8.0.1
    - 8.1.0
